apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kube-system
  name: sample-controller-config
data:
  config: |
    enabled: true
    plugins:
      myplugin:
        enabled: true
        foo: bar
    clusterid: "mycluster"
